flowchart TD
    subgraph Lane_Cust [KHACH THUE - Customer]
        StartContract((Bat dau))
        Cust_Choose[Chon phong va Nop CCCD]
        Cust_Deposit[Dong tien dat coc]
        Cust_CheckIn[Nhan phong va Ban giao thiet bi]
        EndContract((Ket thuc))
    end

    subgraph Lane_Staff [NHAN VIEN - Staff]
        Staff_FindRoom[Kiem tra danh muc phong trong AVAILABLE]
        Staff_CheckCCCD{Xac thuc CCCD 12 so}
        Staff_CreateDraft[Lap hop dong va Dieu khoan]
        Staff_Handover[Lap bien ban ban giao thiet bi]
    end

    subgraph Lane_Sys [HE THONG - Core System]
        Sys_ValCCCD[Validate dinh dang so CCCD]
        Sys_SaveContract[Luu thong tin Contract vao CSDL]
        Sys_ChangeStatus[Chuyen trang thai phong: AVAILABLE -> RENTED]
    end

    StartContract --> Cust_Choose
    Cust_Choose --> Staff_FindRoom
    Staff_FindRoom --> Staff_CheckCCCD
    Staff_CheckCCCD -- Hop le --> Sys_ValCCCD
    Staff_CheckCCCD -- Khong hop le --> Cust_Choose
    Sys_ValCCCD --> Staff_CreateDraft
    Staff_CreateDraft --> Cust_Deposit
    Cust_Deposit --> Sys_SaveContract
    Sys_SaveContract --> Sys_ChangeStatus
    Sys_ChangeStatus --> Staff_Handover
    Staff_Handover --> Cust_CheckIn
    Cust_CheckIn --> EndContract
